batch_size = 1

[model.encoder.T]
feature_size = 768
model = "roberta-large"

[model.encoder.A]
feature_size = 768
model = "facebook/data2vec-audio-base-960h"

[model.encoder.V]
feature_size = 768
model = "google/vivit-b-16x2-kinetics400"
