[model.encoder.T]
feature_size = 768
model = "roberta-large"

[model.encoder.A]
feature_size = 768
model = "facebook/data2vec-audio-base-960h"

[model.encoder.V]
feature_size = 768
model = "MCG-NJU/videomae-base-finetuned-kinetics"
