[project]
name = "emotion-recognition"
version = "0.1.0"
description = ""
authors = [{ name = "Zhan Rongrui", email = "2742392377@qq.com" }]
dependencies = [
    "torch>=2.2.2",
    "transformers>=4.38.2",
    "peft>=0.8.2",
    "safetensors>=0.4.2",
    "cachetools>=5.3.2",
    "loguru>=0.7.0",
    "pydantic>=2.0.0",
    "rich>=13.7.1",
    "soundfile>=0.12.1",
    "whisperx>=3.1.4",
]
requires-python = ">=3.11"
readme = "README.md"
license = { text = "MIT" }

[project.optional-dependencies]
triton = [
    "triton>=2.2.0",
]

[project.urls]
Homepage = "https://github.com/zrr1999/emotion-recognition.git"
Repository = "https://github.com/zrr1999/emotion-recognition.git"

[project.scripts]
emotion-recognize = "recognize.cli:app"

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["F", "I", "B", "C4", "PGH", "RUF", "W", "YTT"]
ignore = ["F841"]

[tool.ruff.lint.isort]
known-first-party = ["recognize"]
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "I002"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[[tool.pdm.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu121"
include_packages = ["torch", "torchvision", "torchaudio"]

[tool.pdm.build]
includes = [
    "recognize",
]
source-includes = ["cli", "README.md"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
