[project]
name = "emotion-recognition"
version = "0.1.0"
description = ""
authors = [{ name = "Zhan Rongrui", email = "2742392377@qq.com" }]
dependencies = []
requires-python = ">=3.11"
readme = "README.md"
license = { text = "MIT" }

[project.urls]
Homepage = "https://pypi.org/project/emotion-recognition"
Repository = "https://github.com/zrr1999/emotion-recognition.git"

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = ["F", "I", "B", "C4", "PGH", "RUF", "W", "YTT"]
ignore = ["F841"]

[tool.ruff.lint.isort]
known-first-party = ["recognize"]
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "I002"]

[tool.pdm.build]
package-dir = "recognize"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
