[semantic_release.remote]
token = { env = "GH_TOKEN" }

[semantic_release.commit_parser_options]
allowed_tags = [
  ".+?breaking",
  ".+?init",
  ".+?feat",
  ".+?fix",
  ".+?refactor",
  ".+?perf",
  ".+?improve",
  ".+?style",
  ".+?test",
  ".+?docs",
  ".+?ci",
  ".+?build",
  ".+?chore",
  ".+?deps",
]
major_tags = [".+?breaking"]
minor_tags = [
  ".+?init",
  ".+?feat",
]
patch_tags = [
  ".+?fix",
  ".+?refactor",
  ".+?perf",
  ".+?improve",
  ".+?style",
  ".+?test",
  ".+?docs",
  ".+?ci",
  ".+?build",
  ".+?chore",
  ".+?deps",
]
