[model]
modals = ["T", "A", "V"]
feature_sizes = [768, 768, 768]
encoders = [
    "roberta-large@checkpoints/training/MELD--E/trainable--1xE--T+A+V#9b0e811e",
    "facebook/wav2vec2-base-960h@checkpoints/training/MELD--E/trainable--1xE--T+A+V#9b0e811e",
    "google/vivit-b-16x2-kinetics400@checkpoints/training/MELD--E/trainable--1xE--T+A+V#9b0e811e",
]
