log_level = "DEBUG"
batch_size = 1

[model]
modals = ["A", "V"]
feature_sizes = [768, 768]
encoders = [
    "facebook/wav2vec2-base-960h",
    "google/vivit-b-16x2-kinetics400",
]
fusion = "LowRankFusionLayer(feature_sizes_dict, 16, 128)"
training_mode = "trainable"
