log_level = "DEBUG"
batch_size = 8

[model]
modals = ["A", "V"]
feature_sizes = [768, 768]
encoders = [
    "facebook/wav2vec2-base-960h",
    "google/vivit-b-16x2-kinetics400",
]
fusion = "LowRankFusionLayer({'A': 768, 'V': 768}, 16, 128)"
training_mode = "frozen"
