log_level = "DEBUG"
batch_size = 1

[model]
modals = ["A", "V"]
feature_sizes = [256, 256]
encoders = [
    "facebook/wav2vec2-base-960h",
    "google/vivit-b-16x2-kinetics400",
]
fusion = "LowRankFusionLayer({'A': 256, 'V': 256}, 16, 128)"
freeze_backbone = false
