log_level = "INFO"

[model]
modals = ["T"]
feature_sizes = [128]
backbones = ["sentence-transformers/all-mpnet-base-v2"]
freeze_backbone = true

[dataset]
path = "datasets/MELD"
label_type = "sentiment"
