log_level = "INFO"
batch_size = 128

[model]
modals = ["T"]
feature_sizes = [768]
encoders = ["roberta-large"]
freeze_backbone = true

[dataset]
dataset_class = "MELDDataset"
path = "datasets/MELD"
label_type = "emotion"
