log_level = "DEBUG"

[model]
modals = ["T", "A"]
feature_sizes = [768, 768]
encoders = [
    "roberta-large",
    "facebook/wav2vec2-base-960h",
]
fusion = "LowRankFusionLayer([768, 768, 1], 16, 128)"
freeze_backbone = false

[dataset]
path = "datasets/MELD"
label_type = "emotion"
