log_level = "INFO"
batch_size = 32

[model]
modals = ["T", "A", "V"]
feature_sizes = [128, 32, 16]
encoders = [
    "roberta-large",
    "facebook/wav2vec2-base-960h",
    "google/vivit-b-16x2-kinetics400",
]
fusion = "LowRankFusionLayer({'T': 128, 'A': 32, 'V': 16}, 16, 128)"
freeze_backbone = false

[dataset]
dataset_class = "PilotDataset"
path = "datasets/pilot-emotion"
label_type = "sentiment"
