log_level = "INFO"
batch_size = 2

[model]
modals = ["T"]
feature_sizes = [128]
encoders = ["roberta-large"]
freeze_backbone = false

[dataset]
dataset_class = "PilotDataset"
path = "datasets/pilot-emotion"
label_type = "sentiment"
