log_level = "DEBUG"
batch_size = 1

[model]
modals = ["T", "A", "V"]
feature_sizes = [768, 256, 256]
encoders = [
    "roberta-large",
    "facebook/wav2vec2-base-960h",
    "google/vivit-b-16x2-kinetics400",
]
fusion = "LowRankFusionLayer({'T': 768, 'A': 256, 'V': 256}, 16, 128)"
training_mode = "trainable"
