log_level = "DEBUG"

[model]
modals = ["T", "A"]
feature_sizes = [768, 256]
encoders = [
    "roberta-large",
    "facebook/wav2vec2-base-960h",
]
fusion = "LowRankFusionLayer({'T': 768, 'A': 256, 'V': 32}, 16, 128)"
freeze_backbone = true

[dataset]
dataset_class = "MELDDataset"
path = "datasets/MELD"
label_type = "emotion"
