log_level = "DEBUG"
batch_size = 4

[model]
modals = ["T", "A"]
feature_sizes = [768, 768]
encoders = [
    "roberta-large",
    "facebook/wav2vec2-base-960h",
]
fusion = "LowRankFusionLayer(feature_sizes_dict, 16, 128)"
training_mode = "trainable"
