log_level = "DEBUG"
batch_size = 4

[model]
modals = ["T", "A"]
feature_sizes = [768, 256]
encoders = [
    "roberta-large",
    "facebook/wav2vec2-base-960h",
]
fusion = "LowRankFusionLayer({'T': 768, 'A': 256, 'V': 32}, 16, 128)"
freeze_backbone = false
