log_level = "DEBUG"

[model]
modals = ["T", "A"]
feature_sizes = [768, 256]
encoders = [
    "roberta-large",
    "facebook/wav2vec2-base-960h",
]
fusion = "LowRankFusionLayer(feature_sizes_dict, 16, 128)"
training_mode = "frozen"

[dataset]
dataset_class = "MELDDataset"
path = "datasets/MELD"
label_type = "emotion"
