log_level = "DEBUG"
batch_size = 1

[model]
modals = ["T", "V"]
feature_sizes = [768, 768]
encoders = [
    "roberta-large",
    "google/vivit-b-16x2-kinetics400",
]
fusion = "LowRankFusionLayer(feature_sizes_dict, 16, 128)"
training_mode = "trainable"
