log_level = "INFO"
batch_size = 128

[model]
modals = ["T"]
feature_sizes = [768]
encoders = ["roberta-large@checkpoints/training/MELD--E/T+A--T"]
training_mode = "frozen"

[dataset]
dataset_class = "MELDDataset"
path = "datasets/MELD"
label_type = "emotion"
